DOMAIN = "energa_outages"

CONF_ZONES = "zones"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_PLANNED_WINDOW_DAYS = "planned_window_days"

DEFAULT_SCAN_INTERVAL = 300  # seconds (5 minutes)
MIN_SCAN_INTERVAL = 60
MAX_SCAN_INTERVAL = 3600

DEFAULT_PLANNED_WINDOW_DAYS = 7
MIN_PLANNED_WINDOW_DAYS = 1
MAX_PLANNED_WINDOW_DAYS = 14
